version: '2.1'

services:
  lua:
    build: .
    environment:
      - LUA_PATH=/test/src/?.lua;/test/src/?/init.lua;/test/spec/?.lua;
      - LUAROCKS_API_KEY=${LUAROCKS_API_KEY}
    volumes:
      - .:/test

